#if  defined(STM32F101xG) || defined(STM32F103xG)
if(__HAL_FLASH_GET_FLAG(FLASH_FLAG_WRPERR) || __HAL_FLASH_GET_FLAG(FLASH_FLAG_WRPERR_BANK2))
#else
  if(__HAL_FLASH_GET_FLAG(FLASH_FLAG_WRPERR))
#endif /* STM32F101xG || STM32F103xG */
  {
    pFlash.ErrorCode |= HAL_FLASH_ERROR_WRP;
  }
