dmaData_t dmatesttypes[NUMDMATYPES] = {
	VME_DMA_PATTERN_BYTE,
	VME_DMA_PATTERN_BYTE_INCREMENT,
	VME_DMA_PATTERN_WORD,
	VME_DMA_PATTERN_WORD_INCREMENT,
	VME_DMA_USER
#if	0
	VME_DMA_KERNEL,
	VME_DMA_PCI,
	VME_DMA_VME
#endif
};
