MTAB tq_mod[] = {
    { MTUF_WLK,         0, "write enabled",  "WRITEENABLED", 
        NULL, NULL, NULL, "Write enable tape drive" },
    { MTUF_WLK,  MTUF_WLK, "write locked",   "LOCKED", 
        NULL, NULL, NULL, "Write lock tape drive"  },
    { MTAB_XTD|MTAB_VDV,  TQ5_TYPE,           NULL,   "TK50",
        &tq_set_type, NULL, NULL, "Set TK50 Device Type" },
    { MTAB_XTD|MTAB_VDV,  TQ7_TYPE,           NULL,   "TK70",
        &tq_set_type, NULL, NULL, "Set TK70 Device Type"  },
    { MTAB_XTD|MTAB_VDV,  TQ8_TYPE,           NULL,  "TU81",
        &tq_set_type, NULL, NULL, "Set TU81 Device Type"  },
    { MTAB_XTD|MTAB_VDV,  TQU_TYPE,           NULL,  "TKUSER",
        &tq_set_type, NULL, NULL, "Set TKUSER=size Device Type"  },
    { MTAB_XTD|MTAB_VDV,         0,         "TYPE",  NULL,
        NULL, &tq_show_type, NULL, "Display device type" },
    { MTAB_XTD|MTAB_VDV|MTAB_NMO, TQ_SH_RI, "RINGS", NULL,
        NULL, &tq_show_ctrl, NULL, "Display command and response rings" },
    { MTAB_XTD|MTAB_VDV|MTAB_NMO, TQ_SH_FR, "FREEQ", NULL,
        NULL, &tq_show_ctrl, NULL, "Display free queue" },
    { MTAB_XTD|MTAB_VDV|MTAB_NMO, TQ_SH_RS, "RESPQ", NULL,
        NULL, &tq_show_ctrl, NULL, "Display response queue" },
    { MTAB_XTD|MTAB_VDV|MTAB_NMO, TQ_SH_UN, "UNITQ", NULL,
        NULL, &tq_show_ctrl, NULL, "Display all unit queues" },
    { MTAB_XTD|MTAB_VDV|MTAB_NMO, TQ_SH_ALL, "ALL", NULL,
        NULL, &tq_show_ctrl, NULL, "Display complete controller state" },
    { MTAB_XTD|MTAB_VUN|MTAB_NMO, 0,        "UNITQ", NULL,
        NULL, &tq_show_unitq, NULL, "Display unit queue" },
    { MTAB_XTD|MTAB_VUN|MTAB_VALR, 0,       "FORMAT", "FORMAT",
        &sim_tape_set_fmt, &sim_tape_show_fmt, NULL, "Set/Display tape format (SIMH, E11, TPC, P7B)" },
    { MTAB_XTD|MTAB_VUN|MTAB_VALR, 0,       "CAPACITY", "CAPACITY",
        &sim_tape_set_capac, &sim_tape_show_capac, NULL, "Set/Display capacity" },
#if defined (VM_PDP11)
    { MTAB_XTD|MTAB_VDV|MTAB_VALR, 004,     "ADDRESS", "ADDRESS",
        &set_addr, &show_addr, NULL, "Bus address" },
    { MTAB_XTD|MTAB_VDV|MTAB_VALR, 0, NULL, "AUTOCONFIGURE",
        &set_addr_flt, NULL, NULL, "Enable autoconfiguration of address & vector" },
#else
    { MTAB_XTD|MTAB_VDV, 004,               "ADDRESS", NULL,
        NULL, &show_addr, NULL, "Bus address" },
#endif
    { MTAB_XTD|MTAB_VDV, 0,                 "VECTOR", NULL,
        NULL, &show_vec, NULL, "Interrupt vector" },
    { 0 }
    };
