static const MTAB vh_mod[] = {
#if !UNIBUS
    { UNIT_MODEDHU,            0, "DHV mode", "DHV", 
        &vh_setmode, NULL,  NULL, "Set DHV mode" },
#endif
    { UNIT_MODEDHU, UNIT_MODEDHU, "DHU mode", "DHU", 
        &vh_setmode, NULL,  NULL, "Set DHU mode" },
    { UNIT_FASTDMA,            0, NULL,       "NORMAL",
        NULL,        NULL,  NULL, "Set Normal DMA mode" },
    { UNIT_FASTDMA, UNIT_FASTDMA, "fast DMA", "FASTDMA", 
        NULL,        NULL,  NULL, "Enable Fast DMA mode" },
    { UNIT_MODEM,              0, NULL,       "NOMODEM",
        NULL,        NULL,  NULL, "Disable modem control" },
    { UNIT_MODEM,     UNIT_MODEM, "Modem",    "MODEM", 
        NULL,        NULL,  NULL, "Enable modem control" },
    { UNIT_HANGUP,             0, NULL,       "NOHANGUP",
        NULL,        NULL,  NULL, "Disable disconnect on DTR drop" },
    { UNIT_HANGUP,   UNIT_HANGUP, "Hangup",   "HANGUP",
        NULL,        NULL,  NULL, "Enable disconnect on DTR drop" },
    { MTAB_XTD|MTAB_VDV|MTAB_VALR, 020, "ADDRESS", "ADDRESS",
        &set_addr, &show_addr, NULL, "Bus address" },
    { MTAB_XTD|MTAB_VDV|MTAB_VALR, 0, "VECTOR", "VECTOR",
        &set_vec, &vh_show_vec, (void *) &vh_desc, "Interrupt vector" },
    { MTAB_XTD|MTAB_VDV, 0, NULL, "AUTOCONFIGURE",
        &set_addr_flt, NULL, NULL, "Enable autoconfiguration of address & vector" },
    { MTAB_XTD|MTAB_VDV|MTAB_VALR, 0, "LINES", "LINES=n",
        &vh_setnl, &tmxr_show_lines, (void *) &vh_desc, "Display number of lines" },
    { UNIT_ATT,         UNIT_ATT, "summary", NULL,
        NULL, &tmxr_show_summ, (void *) &vh_desc, "Display a summary of line states"  },
    { MTAB_XTD|MTAB_VDV|MTAB_NMO, 1, "CONNECTIONS", NULL,
        NULL, &tmxr_show_cstat, (void *) &vh_desc, "Display current connections" },
    { MTAB_XTD|MTAB_VDV|MTAB_NMO, 0, "STATISTICS", NULL,
        NULL, &tmxr_show_cstat, (void *) &vh_desc, "Display multiplexer statistics" },
    { MTAB_XTD|MTAB_VDV|MTAB_VALR, 1, NULL, "DISCONNECT",
        &tmxr_dscln, NULL, &vh_desc, "Disconnect a specific line" },
    { MTAB_XTD|MTAB_VDV|MTAB_NMO, 0, "DETAIL", NULL,
        NULL, &vh_show_detail, NULL, "Display detailed multiplexer status" },
    { MTAB_XTD|MTAB_VDV|MTAB_NMO, 0, "RBUF", NULL,
        NULL, &vh_show_rbuf, NULL, "Display recieve buffer" },
    { MTAB_XTD|MTAB_VDV|MTAB_NMO, 0, "TXQ", NULL,
        NULL, &vh_show_txq, NULL, "Display transmit queue for each mux" },
    { MTAB_XTD|MTAB_VDV|MTAB_NC, 0, NULL, "LOG=n=file",
        &vh_set_log, NULL, &vh_desc, "Display logging"  },
    { MTAB_XTD|MTAB_VDV|MTAB_VALR, 0, NULL, "NOLOG",
        &vh_set_nolog, NULL, &vh_desc, "Disable logging on designated line" },
    { MTAB_XTD|MTAB_VDV|MTAB_NMO, 0, "LOG", NULL,
        NULL, &vh_show_log, &vh_desc, "Display logging for all lines" },
    { 0 }
};
