MTAB rq_mod[] = {
    { UNIT_WLK,                 0,  NULL, "WRITEENABLED", 
        &rq_set_wlk, NULL, NULL, "Write enable disk drive" },
    { UNIT_WLK,          UNIT_WLK,  NULL, "LOCKED", 
        &rq_set_wlk, NULL, NULL, "Write lock disk drive"  },
    { MTAB_XTD|MTAB_VUN, 0, "WRITE", NULL,
      NULL, &rq_show_wlk, NULL,  "Display drive writelock status" },
    { MTAB_XTD|MTAB_VDV|MTAB_NMO, RQ_SH_RI, "RINGS", NULL,
      NULL, &rq_show_ctrl, NULL, "Display command and response rings" },
    { MTAB_XTD|MTAB_VDV|MTAB_NMO, RQ_SH_FR, "FREEQ", NULL,
      NULL, &rq_show_ctrl, NULL, "Display free queue" },
    { MTAB_XTD|MTAB_VDV|MTAB_NMO, RQ_SH_RS, "RESPQ", NULL,
      NULL, &rq_show_ctrl, NULL, "Display response queue" },
    { MTAB_XTD|MTAB_VDV|MTAB_NMO, RQ_SH_UN, "UNITQ", NULL,
      NULL, &rq_show_ctrl, NULL, "Display all unit queues" },
    { MTAB_XTD|MTAB_VDV|MTAB_NMO, RQ_SH_ALL, "ALL", NULL,
      NULL, &rq_show_ctrl, NULL, "Display complete controller state" },
    { MTAB_XTD|MTAB_VDV, RQDX3_CTYPE, NULL, "RQDX3",
      &rq_set_ctype, NULL, NULL, "Set RQDX3 (QBUS RX50/RDnn) Controller Type" },
    { MTAB_XTD|MTAB_VDV, UDA50_CTYPE, NULL, "UDA50",
      &rq_set_ctype, NULL, NULL, "Set UDA50 (UNIBUS SDI RAnn) Controller Type" },
    { MTAB_XTD|MTAB_VDV, KDA50_CTYPE, NULL, "KDA50",
      &rq_set_ctype, NULL, NULL, "Set KDA50 (QBUS SDI RAnn) Controller Type" },
    { MTAB_XTD|MTAB_VDV, KRQ50_CTYPE, NULL, "KRQ50",
      &rq_set_ctype, NULL, NULL, "Set KRQ50 (QBUS CDROM) Controller Type" },
    { MTAB_XTD|MTAB_VDV, KRU50_CTYPE, NULL, "KRU50",
      &rq_set_ctype, NULL, NULL, "Set KRU50 (UNIBUS CDROM) Controller Type" },
    { MTAB_XTD|MTAB_VDV, KLESI_CTYPE, NULL, "KLESI",
      &rq_set_ctype, NULL, NULL, "Set KLESI (RC25) Controller Type"  },
    { MTAB_XTD|MTAB_VDV, RUX50_CTYPE, NULL, "RUX50",
      &rq_set_ctype, NULL, NULL, "Set RUX50 (UNIBUS RX50) Controller Type" },
    { MTAB_XTD|MTAB_VUN|MTAB_NMO, 0, "UNITQ", NULL,
      NULL, &rq_show_unitq, NULL, "Display unit queue" },
    { MTAB_XTD|MTAB_VUN, RX50_DTYPE, NULL, "RX50",
      &rq_set_type, NULL, NULL, "Set RX50 Disk Type" },
    { MTAB_XTD|MTAB_VUN, RX33_DTYPE, NULL, "RX33",
      &rq_set_type, NULL, NULL, "Set RX33 Disk Type" },
    { MTAB_XTD|MTAB_VUN, RD31_DTYPE, NULL, "RD31",
      &rq_set_type, NULL, NULL, "Set RD31 Disk Type" },
    { MTAB_XTD|MTAB_VUN, RD32_DTYPE, NULL, "RD32",
      &rq_set_type, NULL, NULL, "Set RD32 Disk Type" },
    { MTAB_XTD|MTAB_VUN, RD51_DTYPE, NULL, "RD51",
      &rq_set_type, NULL, NULL, "Set RD51 Disk Type" },
    { MTAB_XTD|MTAB_VUN, RD52_DTYPE, NULL, "RD52",
      &rq_set_type, NULL, NULL, "Set RD52 Disk Type" },
    { MTAB_XTD|MTAB_VUN, RD53_DTYPE, NULL, "RD53",
      &rq_set_type, NULL, NULL, "Set RD53 Disk Type" },
    { MTAB_XTD|MTAB_VUN, RD54_DTYPE, NULL, "RD54",
      &rq_set_type, NULL, NULL, "Set RD54 Disk Type" },
    { MTAB_XTD|MTAB_VUN, RA60_DTYPE, NULL, "RA60",
      &rq_set_type, NULL, NULL, "Set RA60 Disk Type" },
    { MTAB_XTD|MTAB_VUN, RA81_DTYPE, NULL, "RA81",
      &rq_set_type, NULL, NULL, "Set RA81 Disk Type" },
    { MTAB_XTD|MTAB_VUN, RA82_DTYPE, NULL, "RA82",
      &rq_set_type, NULL, NULL, "Set RA82 Disk Type" },
    { MTAB_XTD|MTAB_VUN, RRD40_DTYPE, NULL, "RRD40",
      &rq_set_type, NULL, NULL, "Set RRD40 Disk Type" },
    { MTAB_XTD|MTAB_VUN, RRD40_DTYPE, NULL, "CDROM",
      &rq_set_type, NULL, NULL, "Set CDROM Disk Type" },
    { MTAB_XTD|MTAB_VUN, RA70_DTYPE, NULL, "RA70",
      &rq_set_type, NULL, NULL, "Set RA70 Disk Type" },
    { MTAB_XTD|MTAB_VUN, RA71_DTYPE, NULL, "RA71",
      &rq_set_type, NULL, NULL, "Set RA71 Disk Type" },
    { MTAB_XTD|MTAB_VUN, RA72_DTYPE, NULL, "RA72",
      &rq_set_type, NULL, NULL, "Set RA72 Disk Type" },
    { MTAB_XTD|MTAB_VUN, RA73_DTYPE, NULL, "RA73",
      &rq_set_type, NULL, NULL, "Set RA73 Disk Type" },
    { MTAB_XTD|MTAB_VUN, RA90_DTYPE, NULL, "RA90",
      &rq_set_type, NULL, NULL, "Set RA90 Disk Type" },
    { MTAB_XTD|MTAB_VUN, RA92_DTYPE, NULL, "RA92",
      &rq_set_type, NULL, NULL, "Set RA92 Disk Type" },
    { MTAB_XTD|MTAB_VUN, RC25_DTYPE, NULL, "RC25",
      &rq_set_type, NULL, NULL, "Set RC25 Disk Type" },
    { MTAB_XTD|MTAB_VUN, RCF25_DTYPE, NULL, "RCF25",
      &rq_set_type, NULL, NULL, "Set RCF25 Disk Type" },
    { MTAB_XTD|MTAB_VUN, RA80_DTYPE, NULL, "RA80",
      &rq_set_type, NULL, NULL, "Set RA80 Disk Type" },
    { MTAB_XTD|MTAB_VUN|MTAB_VALR, RA8U_DTYPE, NULL, "RAUSER=SIZE",
      &rq_set_type, NULL, NULL, "Set RAUSER=size Disk Type" },
    { MTAB_XTD|MTAB_VUN, 0, "TYPE", NULL,
      NULL, &rq_show_type, NULL, "Display device type" },
    { UNIT_NOAUTO, UNIT_NOAUTO, "noautosize", "NOAUTOSIZE", NULL, NULL, NULL, "Disables disk autosize on attach" },
    { UNIT_NOAUTO,           0, "autosize",   "AUTOSIZE",   NULL, NULL, NULL, "Enables disk autosize on attach" },
    { MTAB_XTD|MTAB_VUN|MTAB_VALR, 0, "FORMAT", "FORMAT={SIMH|VHD|RAW}",
      &sim_disk_set_fmt, &sim_disk_show_fmt, NULL, "Display disk format" },
#if defined (VM_PDP11)
    { MTAB_XTD|MTAB_VDV|MTAB_VALR, 004, "ADDRESS", "ADDRESS",
      &set_addr, &show_addr, NULL, "Bus address" },
    { MTAB_XTD | MTAB_VDV, 0, NULL, "AUTOCONFIGURE",
      &set_addr_flt, NULL, NULL, "Enable autoconfiguration of address & vector" },
#else
    { MTAB_XTD|MTAB_VDV, 004, "ADDRESS", NULL,
      NULL, &show_addr, NULL, "Bus address" },
#endif
    { MTAB_XTD|MTAB_VDV, 0, "VECTOR", NULL,
      NULL, &show_vec, NULL, "Interrupt vector" },
    { MTAB_XTD | MTAB_VDV, 0, "TYPE", NULL,
      NULL, &rq_show_ctype, NULL, "Display controller type" },
    { 0 }
    };
