static CTAB cmd_table[] = {
    { "RESET",      &reset_cmd,     0,          HLP_RESET },
    { "EXAMINE",    &exdep_cmd,     EX_E,       HLP_EXAMINE },
    { "IEXAMINE",   &exdep_cmd,     EX_E+EX_I,  HLP_IEXAMINE },
    { "DEPOSIT",    &exdep_cmd,     EX_D,       HLP_DEPOSIT },
    { "IDEPOSIT",   &exdep_cmd,     EX_D+EX_I,  HLP_IDEPOSIT },
    { "EVALUATE",   &eval_cmd,      0,          HLP_EVALUATE },
    { "RUN",        &run_cmd,       RU_RUN,     HLP_RUN,        NULL, &run_cmd_message },
    { "GO",         &run_cmd,       RU_GO,      HLP_GO,         NULL, &run_cmd_message },
    { "STEP",       &run_cmd,       RU_STEP,    HLP_STEP,       NULL, &run_cmd_message },
    { "NEXT",       &run_cmd,       RU_NEXT,    HLP_NEXT,       NULL, &run_cmd_message },
    { "CONTINUE",   &run_cmd,       RU_CONT,    HLP_CONTINUE,   NULL, &run_cmd_message },
    { "BOOT",       &run_cmd,       RU_BOOT,    HLP_BOOT,       NULL, &run_cmd_message },
    { "BREAK",      &brk_cmd,       SSH_ST,     HLP_BREAK },
    { "NOBREAK",    &brk_cmd,       SSH_CL,     HLP_NOBREAK },
    { "ATTACH",     &attach_cmd,    0,          HLP_ATTACH },
    { "DETACH",     &detach_cmd,    0,          HLP_DETACH },
    { "ASSIGN",     &assign_cmd,    0,          HLP_ASSIGN },
    { "DEASSIGN",   &deassign_cmd,  0,          HLP_DEASSIGN },
    { "SAVE",       &save_cmd,      0,          HLP_SAVE  },
    { "RESTORE",    &restore_cmd,   0,          HLP_RESTORE },
    { "GET",        &restore_cmd,   0,          NULL },
    { "LOAD",       &load_cmd,      0,          HLP_LOAD },
    { "DUMP",       &load_cmd,      1,          HLP_DUMP },
    { "EXIT",       &exit_cmd,      0,          HLP_EXIT },
    { "QUIT",       &exit_cmd,      0,          NULL },
    { "BYE",        &exit_cmd,      0,          NULL },
    { "CD",         &set_default_cmd, 0,        HLP_CD },
    { "PWD",        &pwd_cmd,       0,          HLP_PWD },
    { "DIR",        &dir_cmd,       0,          HLP_DIR },
    { "LS",         &dir_cmd,       0,          HLP_LS },
    { "SET",        &set_cmd,       0,          HLP_SET },
    { "SHOW",       &show_cmd,      0,          HLP_SHOW },
    { "DO",         &do_cmd,        1,          HLP_DO },
    { "GOTO",       &goto_cmd,      1,          HLP_GOTO },
    { "RETURN",     &return_cmd,    0,          HLP_RETURN },
    { "SHIFT",      &shift_cmd,     0,          HLP_SHIFT },
    { "CALL",       &call_cmd,      0,          HLP_CALL },
    { "ON",         &on_cmd,        0,          HLP_ON },
    { "IF",         &assert_cmd,    0,          HLP_IF },
    { "PROCEED",    &noop_cmd,      0,          HLP_PROCEED },
    { "IGNORE",     &noop_cmd,      0,          HLP_IGNORE },
    { "ECHO",       &echo_cmd,      0,          HLP_ECHO },
    { "ASSERT",     &assert_cmd,    1,          HLP_ASSERT },
    { "SEND",       &send_cmd,      0,          HLP_SEND },
    { "EXPECT",     &expect_cmd,    1,          HLP_EXPECT },
    { "NOEXPECT",   &expect_cmd,    0,          HLP_EXPECT },
    { "!",          &spawn_cmd,     0,          HLP_SPAWN },
    { "HELP",       &help_cmd,      0,          HLP_HELP },
#if defined(USE_SIM_VIDEO)
    { "SCREENSHOT", &screenshot_cmd,0,          HLP_SCREENSHOT },
#endif
    { NULL, NULL, 0 }
    };
