static struct class_attribute amvecm_class_attrs[] = {
	__ATTR(dnlp, S_IRUGO | S_IWUSR,
		amvecm_dnlp_show, amvecm_dnlp_store),
	__ATTR(brightness, S_IRUGO | S_IWUSR,
		amvecm_brightness_show, amvecm_brightness_store),
	__ATTR(contrast, S_IRUGO | S_IWUSR,
		amvecm_contrast_show, amvecm_contrast_store),
	__ATTR(saturation_hue,S_IRUGO | S_IWUSR,
		amvecm_saturation_hue_show,
		amvecm_saturation_hue_store),
	__ATTR(saturation_hue1,S_IRUGO | S_IWUSR,
		video_adj1_saturation_hue_show,
		video_adj1_saturation_hue_store),
	__ATTR(saturation_hue2,S_IRUGO | S_IWUSR,
		video_adj2_saturation_hue_show,
		video_adj2_saturation_hue_store),
	__ATTR(cm2,S_IRUGO | S_IWUSR,
		amvecm_cm2_show,
		amvecm_cm2_store),
	__ATTR(gamma,S_IRUGO | S_IWUSR,
		amvecm_gamma_show,
		amvecm_gamma_store),
	__ATTR(brightness1, S_IRUGO | S_IWUSR,
		video_adj1_brightness_show, video_adj1_brightness_store),
	__ATTR(contrast1, S_IRUGO | S_IWUSR,
		video_adj1_contrast_show, video_adj1_contrast_store),
	__ATTR(brightness2, S_IRUGO | S_IWUSR,
		video_adj2_brightness_show, video_adj2_brightness_store),
	__ATTR(contrast2, S_IRUGO | S_IWUSR,
		video_adj2_contrast_show, video_adj2_contrast_store),
	__ATTR(help, S_IRUGO | S_IWUSR,
		amvecm_usage_show, NULL),
#if (MESON_CPU_TYPE >= MESON_CPU_TYPE_MESONG9TV)
	__ATTR(sync_3d,S_IRUGO | S_IWUSR,
		amvecm_3d_sync_show,
		amvecm_3d_sync_store),
#endif
	__ATTR(matrix_set, S_IRUGO | S_IWUSR,
		amvecm_set_post_matrix_show, amvecm_set_post_matrix_store),
	__ATTR(matrix_pos, S_IRUGO | S_IWUSR,
		amvecm_post_matrix_pos_show, amvecm_post_matrix_pos_store),
	__ATTR(matrix_data, S_IRUGO | S_IWUSR,
		amvecm_post_matrix_data_show, amvecm_post_matrix_data_store),
	__ATTR_NULL
};
