struct option cpio_longopts[] = {
	{ "reset-access-time",	no_argument,		0,	'a' },
	{ "make-directories",	no_argument,		0, 	'd' },
	{ "nonmatching",	no_argument,		0,	'f' },
	{ "extract",		no_argument,		0,	'i' },
	{ "link",		no_argument,		0,	'l' },
	{ "preserve-modification-time", no_argument,	0,	'm' },
	{ "create",		no_argument,		0,	'o' },
	{ "pass-through",	no_argument,		0,	'p' },
	{ "rename",		no_argument,		0,	'r' },
	{ "list",		no_argument,		0,	't' },
	{ "unconditional",	no_argument,		0,	'u' },
	{ "verbose",		no_argument,		0,	'v' },
	{ "append",		no_argument,		0,	'A' },
	{ "pattern-file",	required_argument,	0,	'E' },
	{ "file",		required_argument,	0,	'F' },
	{ "force-local",	no_argument,		0,
						OPT_FORCE_LOCAL },
	{ "format",		required_argument,	0,	'H' },
	{ "dereference",	no_argument,		0,	'L' },
	{ "swap-halfwords",	no_argument,		0,	'S' },
	{ "insecure",		no_argument,		0,
						OPT_INSECURE },
	{ "sparse",		no_argument,		0,
						OPT_SPARSE },

#ifdef notyet
/* Not implemented */
	{ "null",		no_argument,		0,	'0' },
	{ "swap",		no_argument,		0,	'b' },
	{ "numeric-uid-gid",	no_argument,		0,	'n' },
	{ "swap-bytes",		no_argument,		0,	's' },
	{ "message",		required_argument,	0,	'M' },
	{ "owner",		required_argument,	0	'R' },
	{ "dot",		no_argument,		0,	'V' },
	{ "block-size",		required_argument,	0,
						OPT_BLOCK_SIZE },
	{ "no-absolute-pathnames", no_argument,		0,
						OPT_NO_ABSOLUTE_PATHNAMES },
	{ "no-preserve-owner",	no_argument,		0,
						OPT_NO_PRESERVE_OWNER },
	{ "only-verify-crc",	no_argument,		0,
						OPT_ONLY_VERIFY_CRC },
	{ "rsh-command",	required_argument,	0,
						OPT_RSH_COMMAND },
	{ "version",		no_argument,		0,
						OPT_VERSION },
#endif
	{ 0,			0,			0,	0 },
};
