static bind_t g_bindings[] =
{
	{ "+forward",         'w',             -1,  K_UPARROW,       -1,  -1, -1 },
	{ "+back",            's',             -1,  K_DOWNARROW,     -1,  -1, -1 },
	{ "+moveleft",        'a',             -1,  K_LEFTARROW,     -1,  -1, -1 },
	{ "+moveright",       'd',             -1,  K_RIGHTARROW,    -1,  -1, -1 },
	{ "+moveup",          K_SPACE,         -1,  K_KP_INS,        -1,  -1, -1 },
	{ "+movedown",        'c',             -1,  K_CTRL,          -1,  -1, -1 },
	{ "+leanright",       'e',             -1,  K_PGDN,          -1,  -1, -1 },
	{ "+leanleft",        'q',             -1,  K_DEL,           -1,  -1, -1 },
	{ "+prone",           'x',             -1,  K_SHIFT,         -1,  -1, -1 },
	{ "+attack",          K_MOUSE1,        -1,  K_MOUSE1,        -1,  -1, -1 },
	{ "weapalt",          K_MOUSE2,        -1,  K_MOUSE2,        -1,  -1, -1 },
	{ "weapprev",         K_MWHEELDOWN,    -1,  K_MWHEELDOWN,    -1,  -1, -1 },
	{ "weapnext",         K_MWHEELUP,      -1,  K_MWHEELUP,      -1,  -1, -1 },
	{ "weaponbank 10",    '0',             -1,  '0',             -1,  -1, -1 },
	{ "weaponbank 1",     '1',             -1,  '1',             -1,  -1, -1 },
	{ "weaponbank 2",     '2',             -1,  '2',             -1,  -1, -1 },
	{ "weaponbank 3",     '3',             -1,  '3',             -1,  -1, -1 },
	{ "weaponbank 4",     '4',             -1,  '4',             -1,  -1, -1 },
	{ "weaponbank 5",     '5',             -1,  '5',             -1,  -1, -1 },
	{ "weaponbank 6",     '6',             -1,  '6',             -1,  -1, -1 },
	{ "weaponbank 7",     '7',             -1,  '7',             -1,  -1, -1 },
	{ "weaponbank 8",     '8',             -1,  '8',             -1,  -1, -1 },
	{ "weaponbank 9",     '9',             -1,  '9',             -1,  -1, -1 },
	{ "+sprint",          K_SHIFT,         -1,  K_MOUSE3,        -1,  -1, -1 },
	{ "+speed",           K_CAPSLOCK,      -1,  K_CAPSLOCK,      -1,  -1, -1 },
	{ "+activate",        'f',             -1,  K_ENTER,         -1,  -1, -1 },
	{ "+zoom",            'b',             -1,  'b',             -1,  -1, -1 },
	{ "+mapexpand",       'g',             -1,  '#',             -1,  -1, -1 },
	{ "+reload",          'r',             -1,  K_END,           -1,  -1, -1 },
	{ "kill",             'k',             -1,  'k',             -1,  -1, -1 },
	{ "+scores",          K_TAB,           -1,  K_TAB,           -1,  -1, -1 },
	{ "+stats",           K_ALT,           -1,  K_F9,            -1,  -1, -1 },
	{ "+topshots",        K_CTRL,          -1,  K_F10,           -1,  -1, -1 },
	{ "+objectives",      'o',             -1,  'o',             -1,  -1, -1 },
	{ "toggleconsole",    '`',             '~', '`',             '~', -1, -1 },
	{ "togglemenu",       K_ESCAPE,        -1,  K_ESCAPE,        -1,  -1, -1 },
	{ "openlimbomenu",    'l',             -1,  'l',             -1,  -1, -1 },
#ifdef FEATURE_MULTIVIEW
	{ "mvactivate",       'm',             -1,  'm',             -1,  -1, -1 },
#endif
	{ "mapzoomout",       ',',             -1,  '[',             -1,  -1, -1 },
	{ "mapzoomin",        '.',             -1,  ']',             -1,  -1, -1 },
	{ "zoomin",           '=',             -1,  '-',             -1,  -1, -1 },
	{ "zoomout",          '-',             -1,  '=',             -1,  -1, -1 },
	{ "messagemode",      't',             -1,  't',             -1,  -1, -1 },
	{ "messagemode2",     'y',             -1,  'y',             -1,  -1, -1 },
	{ "messagemode3",     'u',             -1,  'u',             -1,  -1, -1 },
	{ "mp_quickmessage",  'v',             -1,  'v',             -1,  -1, -1 },
	{ "mp_fireteammsg",   'z',             -1,  'c',             -1,  -1, -1 },
	{ "vote yes",         K_F1,            -1,  K_F1,            -1,  -1, -1 },
	{ "vote no",          K_F2,            -1,  K_F2,            -1,  -1, -1 },
	{ "ready",            K_F3,            -1,  K_F3,            -1,  -1, -1 },
	{ "notready",         K_F4,            -1,  K_F4,            -1,  -1, -1 },
	{ "autoscreenshot",   K_F11,           -1,  K_F11,           -1,  -1, -1 },
	{ "autoRecord",       K_F12,           -1,  K_F12,           -1,  -1, -1 },
	{ "mp_fireteamadmin", K_KP_ENTER,      -1,  K_KP_ENTER,      -1,  -1, -1 },
	{ "selectbuddy -1",   K_KP_PLUS,       -1,  K_KP_PLUS,       -1,  -1, -1 },
	{ "selectbuddy 0",    K_KP_END,        -1,  K_KP_END,        -1,  -1, -1 },
	{ "selectbuddy 1",    K_KP_DOWNARROW,  -1,  K_KP_DOWNARROW,  -1,  -1, -1 },
	{ "selectbuddy 2",    K_KP_PGDN,       -1,  K_KP_PGDN,       -1,  -1, -1 },
	{ "selectbuddy 3",    K_KP_LEFTARROW,  -1,  K_KP_LEFTARROW,  -1,  -1, -1 },
	{ "selectbuddy 4",    K_KP_5,          -1,  K_KP_5,          -1,  -1, -1 },
	{ "selectbuddy 5",    K_KP_RIGHTARROW, -1,  K_KP_RIGHTARROW, -1,  -1, -1 },
	{ "selectbuddy 6",    K_KP_HOME,       -1,  K_KP_HOME,       -1,  -1, -1 },
	{ "selectbuddy 7",    K_KP_UPARROW,    -1,  K_KP_UPARROW,    -1,  -1, -1 },
	{ "selectbuddy -2",   K_KP_MINUS,      -1,  K_KP_MINUS,      -1,  -1, -1 },
};
