switch (in) {
	case STATUS_OK:
		return SLURM_SUCCESS;
	case PARTITION_NOT_FOUND:
		return BG_ERROR_BLOCK_NOT_FOUND;
	case INCOMPATIBLE_STATE:
		return BG_ERROR_INVALID_STATE;
	case CONNECTION_ERROR:
		return BG_ERROR_CONNECTION_ERROR;
	case JOB_NOT_FOUND:
		return BG_ERROR_JOB_NOT_FOUND;
	case BP_NOT_FOUND:
		return BG_ERROR_MP_NOT_FOUND;
	case SWITCH_NOT_FOUND:
		return BG_ERROR_SWITCH_NOT_FOUND;
#ifndef HAVE_BGL
	case PARTITION_ALREADY_DEFINED:
		return BG_ERROR_BLOCK_ALREADY_DEFINED;
#endif
	case JOB_ALREADY_DEFINED:
		return BG_ERROR_JOB_ALREADY_DEFINED;
	case INTERNAL_ERROR:
		return BG_ERROR_INTERNAL_ERROR;
	case INVALID_INPUT:
		return BG_ERROR_INVALID_INPUT;
	case INCONSISTENT_DATA:
		return BG_ERROR_INCONSISTENT_DATA;
	default:
		break;
	}
