u8 DRXD_InitDiversityEnd[] = {
	/* End demod *********** combining RF in and diversity in, MPEG TS out **** */
	/* disable near/far; switch on timing slave mode */
	WR16(B_SC_RA_RAM_CONFIG__A, B_SC_RA_RAM_CONFIG_FR_ENABLE__M |
	     B_SC_RA_RAM_CONFIG_FREQSCAN__M |
	     B_SC_RA_RAM_CONFIG_DIV_ECHO_ENABLE__M |
	     B_SC_RA_RAM_CONFIG_SLAVE__M |
	     B_SC_RA_RAM_CONFIG_DIV_BLANK_ENABLE__M
/* MV from CtrlDiversity */
	    ),
#ifdef DRXDDIV_SRMM_SLAVING
	WR16(SC_RA_RAM_LC_ABS_2K__A, 0x3c7),
	WR16(SC_RA_RAM_LC_ABS_8K__A, 0x3c7),
#else
	WR16(SC_RA_RAM_LC_ABS_2K__A, 0x7),
	WR16(SC_RA_RAM_LC_ABS_8K__A, 0x7),
#endif

	WR16(B_SC_RA_RAM_IR_COARSE_8K_LENGTH__A, IRLEN_COARSE_8K),
	WR16(B_SC_RA_RAM_IR_COARSE_8K_FREQINC__A, 1 << (11 - IRLEN_COARSE_8K)),
	WR16(B_SC_RA_RAM_IR_COARSE_8K_KAISINC__A, 1 << (17 - IRLEN_COARSE_8K)),
	WR16(B_SC_RA_RAM_IR_FINE_8K_LENGTH__A, IRLEN_FINE_8K),
	WR16(B_SC_RA_RAM_IR_FINE_8K_FREQINC__A, 1 << (11 - IRLEN_FINE_8K)),
	WR16(B_SC_RA_RAM_IR_FINE_8K_KAISINC__A, 1 << (17 - IRLEN_FINE_8K)),

	WR16(B_SC_RA_RAM_IR_COARSE_2K_LENGTH__A, IRLEN_COARSE_2K),
	WR16(B_SC_RA_RAM_IR_COARSE_2K_FREQINC__A, 1 << (11 - IRLEN_COARSE_2K)),
	WR16(B_SC_RA_RAM_IR_COARSE_2K_KAISINC__A, 1 << (17 - IRLEN_COARSE_2K)),
	WR16(B_SC_RA_RAM_IR_FINE_2K_LENGTH__A, IRLEN_FINE_2K),
	WR16(B_SC_RA_RAM_IR_FINE_2K_FREQINC__A, 1 << (11 - IRLEN_FINE_2K)),
	WR16(B_SC_RA_RAM_IR_FINE_2K_KAISINC__A, 1 << (17 - IRLEN_FINE_2K)),

	WR16(B_LC_RA_RAM_FILTER_CRMM_A__A, 7),
	WR16(B_LC_RA_RAM_FILTER_CRMM_B__A, 4),
	WR16(B_LC_RA_RAM_FILTER_SRMM_A__A, 7),
	WR16(B_LC_RA_RAM_FILTER_SRMM_B__A, 4),
	WR16(B_LC_RA_RAM_FILTER_SYM_SET__A, 500),

	WR16(B_CC_REG_DIVERSITY__A, 0x0001),
	END_OF_TABLE
};
