switch (next_action) {
    case SEARCH_START_CODE:
        WRITE_MPEG_REG(PARSER_CONTROL, PARSER_AUTOSEARCH);
        break;

    case SEND_VIDEO_SEARCH:
        WRITE_MPEG_REG_BITS(PARSER_CONTROL, PARSER_AUTOSEARCH | PARSER_VIDEO | PARSER_WRITE, ES_CTRL_BIT, ES_CTRL_WID);
        break;

    case SEND_AUDIO_SEARCH:
        WRITE_MPEG_REG_BITS(PARSER_CONTROL, PARSER_AUTOSEARCH | PARSER_AUDIO | PARSER_WRITE, ES_CTRL_BIT, ES_CTRL_WID);
        break;

    case SEND_SUBPIC_SEARCH:
        WRITE_MPEG_REG_BITS(PARSER_CONTROL, PARSER_AUTOSEARCH | PARSER_SUBPIC | PARSER_WRITE | ES_INSERT_BEFORE_ES_WRITE, ES_CTRL_BIT, ES_CTRL_WID);
        break;

    case DISCARD_SEARCH:
        WRITE_MPEG_REG_BITS(PARSER_CONTROL, PARSER_AUTOSEARCH | PARSER_DISCARD, ES_CTRL_BIT, ES_CTRL_WID);
        break;

    case DISCARD_ONLY:
        WRITE_MPEG_REG_BITS(PARSER_CONTROL, PARSER_DISCARD, ES_CTRL_BIT, ES_CTRL_WID);
        break;

#ifdef VIDEO_AUTO_FLUSH
    case SEARCH_START_CODE_VIDEO_FLUSH:
        WRITE_MPEG_REG(PARSER_INSERT_DATA, 0xffffffff);
        WRITE_MPEG_REG(PARSER_INSERT_DATA, 0xffffffff);
        WRITE_MPEG_REG(PARSER_PARAMETER, ((VIDEO_AUTO_FLUSH_BYTE_COUNT/8) << PARSER_PARAMETER_LOOP_BIT) | (8 << PARSER_PARAMETER_LENGTH_BIT));
        WRITE_MPEG_REG(PARSER_CONTROL, PARSER_AUTOSEARCH | PARSER_VIDEO | PARSER_WRITE | ES_INSERT_BEFORE_ES_WRITE);
        break;
#endif
    }
