static const struct CLK_BASE_STATES clock_states[] = {
    {CLK_BASE_SAFE, CLKIN_IRC, 0},
    {CLK_BASE_APB1, CLKIN_MAINPLL, 0},
    {CLK_BASE_APB3, CLKIN_MAINPLL, 0},
    {CLK_BASE_USB0, CLKIN_USBPLL, 1},
    {CLK_BASE_PERIPH, CLKIN_MAINPLL, 0},
    {CLK_BASE_SPI, CLKIN_MAINPLL, 0},
    {CLK_BASE_PHY_TX, CLKIN_ENET_TX, 0},
#if defined(USE_RMII)
    {CLK_BASE_PHY_RX, CLKIN_ENET_TX, 0},
#else
    {CLK_BASE_PHY_RX, CLKIN_ENET_RX, 0},
#endif
    {CLK_BASE_SDIO, CLKIN_MAINPLL, 0},
    {CLK_BASE_SSP0, CLKIN_IDIVC, 0},
    {CLK_BASE_SSP1, CLKIN_IDIVC, 0},
    {CLK_BASE_UART0, CLKIN_MAINPLL, 0},
    {CLK_BASE_UART1, CLKIN_MAINPLL, 0},
    {CLK_BASE_UART2, CLKIN_MAINPLL, 0},
    {CLK_BASE_UART3, CLKIN_MAINPLL, 0},
    {CLK_BASE_OUT, CLKINPUT_PD, 0},
    {CLK_BASE_APLL, CLKINPUT_PD, 0},
    {CLK_BASE_CGU_OUT0, CLKINPUT_PD, 0},
    {CLK_BASE_CGU_OUT1, CLKINPUT_PD, 0},

    /* Clocks derived from dividers */
    {CLK_BASE_LCD, CLKIN_IDIVC, 0},
    {CLK_BASE_USB1, CLKIN_IDIVD, 1}
};
