static byte extended_xdi_features[DIVA_XDI_EXTENDED_FEATURES_MAX_SZ + 1] = {
	(DIVA_XDI_EXTENDED_FEATURES_VALID       |
	 DIVA_XDI_EXTENDED_FEATURE_SDRAM_BAR    |
	 DIVA_XDI_EXTENDED_FEATURE_CAPI_PRMS    |
#if defined(DIVA_IDI_RX_DMA)
	 DIVA_XDI_EXTENDED_FEATURE_CMA          |
	 DIVA_XDI_EXTENDED_FEATURE_RX_DMA       |
	 DIVA_XDI_EXTENDED_FEATURE_MANAGEMENT_DMA |
#endif
	 DIVA_XDI_EXTENDED_FEATURE_NO_CANCEL_RC),
	0
};
